use_frameworks!

target 'BLFoundation_Example' do
  pod 'BLFoundation', :path => '../'

  target 'BLFoundation_Tests' do
    inherit! :search_paths

    
  end
end

target 'BLFoundation_watch' do
  pod 'BLFoundation', :path => '../'
end

target 'BLFoundation_watch Extension' do
  pod 'BLFoundation', :path => '../'
end
